[pytest]
# Run tests in module docstrings.  See
# <https://docs.pytest.org/en/stable/how-to/doctest.html#how-to-run-doctests>:
addopts = ["--doctest-modules"]

# Show `logging` output in unit test output:
log_cli = true
log_cli_level = "INFO"
